### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by amzeman** [TIS2024-FMFI/finances#1]
Napísať katalóg požiadaviek

**Comment by pavelpetrovic** [comment]
moje nahodne poznamky ku KP s ktorymi nalozte ako chcete:

- prosim odstranit genericku linku na SAP v odkazoch
- " aj údaje všetkých zamestnancov zdieľajúcich účet" -> o ich operaciach, nie o nich samotnych
- v 2.1. by sa mohlo spomenut aj na sekretarku, ktora bude zo systemu tiez mat uzitok
- 2.2 -> system bude zdielat ucty zamestnancov pouzite v systeme Pritomnost
- zo sveta snov:  spolocne prihlasovanie cez AIS ucty (Shibboleth 2, Zagiba)
- do casti 3 pridat, ze Admin vie pridat alebo odobrat pristup k nejakemu SPP jednotlivym pouzivatelom
- admin moze pridat nove SPP prvky a oznacit existujuce SPP prvky za neaktivne, resp. v pripade omylu aj zmazat
- 2.2 "Používateľ môže pridať nové účty" -> iba admin
- 2.2. "zaznamenávať transakcie" => navrhy transakcii
- 2.2. "Môže exportovať celkový stav účtov" => neviem, co sa za tym skryva
- volne myslienky:
    - export zo SAPu by mala nahravat iba sekretarka ked sa jej zachce
    - priradovat operacie zo SAPu k jednotlivym transakciam, ktore pouzivatelia v systeme navrhli a admin schvalil moze pouzivatel (resp. sekretarka ked je prihlasena ako on cez "LOGIN AS"
 - 2.2. nie som si isty, ci mam jasno v tom, ake vsetky importy a exporty robi kto
 - 3.2.1. prihlasovat jednotne do vsetkych 3 systemov
 - skusme dospiet k zoznamu poziadaviek vsetkych, ktore novy system bude poskytovat - a teda netreba pisat co robit nebude
 - priloha je dobrovolna
 - A16 zoznam typov konfigurovatelny nejak
 - moznost zobrazit temnu hmotu v SAPe
 - admin ucet nie je pouzivtel typu @uniba.sk

**Comment by pavelpetrovic** [comment]
- v uvode ma menujete, ale nie som zadavatel, ak niekoho tak pani Slobodovu
- 1.2 -> schválenie formulárov obsahujúcich informácie o pohyboch na účte-> schválenie účtovných operácií
- výdavkov v systéme ŠPP  => výdavkov a príjmov na účtoch ŠPP so správcami z KAI
- 2.3 -> vydavkov [bezny] -> a príjmov;  admin -> moze tiez vytvarat operacie
- z diskusie vyplynulo: k lubovolnej operacii moze pouzivatel alebo admin nahravat aj viacere prilohy aj dodatocne
- ostava iba na zvazenie ci pridat volitelnu (optional) poziadavku o prihlasovani cez uniba live id (meno123@uniba.sk)
- A3 - co znamena "ma k dispozicii"? vie si zobrazit?
- A7 + A11 -> schvalenie poziadavky na pozicku vyvola zaradenie pohybu na oba ucty
- asi najlepsie v slovniku pojmov alebo v casti 2 vysvetlit ako funguje pohyb "pozicka",
   priklad:   kupujem monitor z SPP1  za 800, pricom mam iba 300 a poziciavam si 500 z uctu SPP2
     na mojom ucte sa objavi polozka pozicka +500 a potom nova polozka vydavok -800.
     na ucte SPP2 sa objavi pozicka -500 a to je vsetko.
    ale v prehlade celkoveho stavu sa na SPP1 zobrazi, vysledny stav: 0, dlh na pozickach: 500
   v prehlade stavu na SPP2 sa zobrazi: vysledny stav: volaco, napr. 100, pohladavky z poziciek: 500
- A13: splacanie poziciek zaeviduje vzdy administrator
- A14: prosim pridat "nespracovane" alebo "neschvalene"
- B2 je pokryte systemom Pritomnost
- B4 mozno by mohla byt optional poziadavka import SPP zo systemu cesty (alebo zo suboru?)
- tie SPP by mali mat kto je spravca a popis
- B6 ak neschvali, tak sa zmaze (a pride mailova notifikacia pouzivatelovi, ktory pohyb zadal)
- B8 vyzera byt redundantna

**Comment by pavelpetrovic** [comment]
nepamatam sa, ako to dopadlo na nasom poslednom stretnuti, ale pohladom do posledneho PDF, co ste mi poslali mailom je tu myslim este problem, ze v casti 2 sa pise:

"Môže nahrať export zo systému SAP."

a v casti 3 o tom nie je nic napisane. :(

Uz teraz ten existujuci system dokaze importnut exportovany vykaz zo SAPu a potom priradovat
jednotlive operacie zadane v systeme k polozkam na vykaze zo SAP.

Toto by sme tam snad chceli nechat?

Je to dolezite kvoli tym uctom, kde viaceri zdielaju ten isty ucet a musia sa prihlasit k jednotlivym operaciam.
Hovorili sme o tom, ze aj k tym bankovym poplatkom a podobnym drobnym operaciam sa niekto musi
prihlasit, lebo celkovy sucet prijmov a vydavkov na tom ucte nakoniec musi sediet.

tusim sme hovorili minule, ze system Cesty, ktory vylepsuju Vasi kolegovia, by mal byt schopny do Vasej databazy nejak pridat pohyb na ucte ohladne vyuctovania cesty, ale iba pre istotu pripominam, ze sa na tom treba dohodnut s tym druhym timom.

**Comment by pavelpetrovic** [comment]
cim skor aktualizujme KP k sucasnej predstave:
  - SPP sa edituju iba cez system cesty a nemazu sa a v tejto aplikacii moze byt presmerovanie na stranku, kde sa daju pridat

navrhujem "optional" poziadavku
 - po schvaleni financovania cesty v systeme cesty bude linka na predvyplneny formular, ktorym moze admin ulozit vyuctovanie cesty aj do systemu SPP, resp. linka na prihlasenie ak nie je prihlaseny.
