### ISSUE TITLE
Návrh - podrobný dátový model 

### ISSUE THREAD

**Issue by MartinKlokocik** [TIS2024-FMFI/finances#12]
Podrobný dátový model perzistentných údajov (napr. [pgadmin](https://www.youtube.com/watch?v=2pxVCzRFGeg)), formátov súborov, komunikačných protokolov.

**Comment by pavelpetrovic** [comment]
![Image](https://github.com/user-attachments/assets/1a40c5d1-98a9-40bc-a327-59b8a9748789)

**Comment by pavelpetrovic** [comment]
![Image](https://github.com/user-attachments/assets/42ebf660-78ba-47af-adf5-00497ef94262)

**Comment by amzeman** [comment]
![Image](https://github.com/user-attachments/assets/7144477a-3aef-4050-97e2-64ef86771b7f)

**Comment by amzeman** [comment]
![Image](https://github.com/user-attachments/assets/389fb5ca-bb88-4c70-964c-00af2ed5e164)
