### ISSUE TITLE
Návrh - používateľské rozhranie 

### ISSUE THREAD

**Issue by MartinKlokocik** [TIS2024-FMFI/finances#13]
Návrh používateľského rozhrania (ak projekt má GUI) - nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom

**Comment by amzeman** [comment]
Moqups.com - wireframy
farby ako stranka fakulty (cervena, ...)
Podobny design ako stranky uniba ...

**Comment by MartinKlokocik** [comment]
https://www.figma.com/design/0sBpzYXCukMe4ektqexzEE/Finances?node-id=0-1&t=SbeVGcVFlmvuxn05-1

**Comment by MartinKlokocik** [comment]
https://app.moqups.com/s4C1hklCr1mDMlTfl6fPygpgC7DFGgCS/view/page/a8629fabc

**Comment by pavelpetrovic** [comment]
prosim pred stretnutim so zadavatelom vyexportovat (napr. aj odfotenim obrazovky do jednej sady vsetkych dialogov/stranok, ktore sa budu pouzivatelom zobrazovat)

**Comment by amzeman** [comment]
Vo Figme sú nahraté vsetky návrhy na ktorých sme sa dohodli:

https://www.figma.com/design/0sBpzYXCukMe4ektqexzEE/Finances?node-id=0-1&t=cVTf38fE04N1mzI0-1

Zároveň prikladám pdf export:

[Finances.pdf](https://github.com/user-attachments/files/18027394/Finances.pdf)
