### ISSUE TITLE
Návrh - Zrozumiteľný a jednoznačný návrh implementácie

### ISSUE THREAD

**Issue by MartinKlokocik** [TIS2024-FMFI/finances#14]
Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

**Comment by MartinKlokocik** [comment]
- UML class diagram = @kihachu 
- UML component diagram = @AdamZeman 
- UML state diagram = @Gurtas1

**Comment by amzeman** [comment]
![Image](https://github.com/user-attachments/assets/4c17836d-bec1-4eec-9459-fef419c9f34a)

**Comment by MartinKlokocik** [comment]
![Image](https://github.com/user-attachments/assets/5b040d6e-a9dd-4ea5-90e9-4c0b5636d550)

**Comment by kihachu** [comment]
![Auth](https://github.com/user-attachments/assets/f3191957-9fa5-42d2-814c-7d998d0b806a)

**Comment by kihachu** [comment]
![Auth](https://github.com/user-attachments/assets/33e2e189-3fa3-421e-817e-045f1b661778)

**Comment by MartinKlokocik** [comment]
![Image](https://github.com/user-attachments/assets/c289fec5-0625-47ae-93a4-288fc97cc18b)
![Image](https://github.com/user-attachments/assets/bcf0b3ed-24e9-4d49-99ee-3b3a838d5ed0)


State Diagram UPDATE

**Comment by amzeman** [comment]
![Image](https://github.com/user-attachments/assets/a8ed2212-88a2-4b63-8612-0da6dc96cf90)
