### ISSUE TITLE
Kompletizovať navrh 6,7,9

### ISSUE THREAD

**Issue by amzeman** [TIS2024-FMFI/finances#38]

**Comment by amzeman** [comment]
Návrh, bod 6,7,9
Poprosil by som update na dannej časti.
Pripomínam, že za issue je zodpovedný ten komu to je pridelené.

**Comment by kihachu** [comment]
[Navrh_our_version4.docx](https://github.com/user-attachments/files/18165747/Navrh_our_version4.docx)
